# Generated by Django 3.2.6 on 2021-12-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211220_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
