# Generated by Django 3.2.6 on 2021-10-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='prezzo',
            field=models.FloatField(default=0),
        ),
    ]
