# Generated by Django 3.2.6 on 2021-10-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_watch_prezzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='maison',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='watch',
            name='modello',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='watch',
            name='movimento',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='watch',
            name='proprietario',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='watch',
            name='referenza',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='watch',
            name='stato',
            field=models.CharField(default='', max_length=20),
        ),
    ]
