# Generated by Django 3.2.6 on 2021-12-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211020_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='stato',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='modello',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='movimento',
            new_name='movement',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='proprietario',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='prezzo',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='referenza',
            new_name='reference',
        ),
    ]
