# Generated by Django 3.2.6 on 2021-12-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_watch_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maison', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='watch',
            name='maison',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.maison'),
        ),
    ]
