# Generated by Django 3.2.6 on 2022-01-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220104_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='maison',
            name='maison',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
