# Generated by Django 3.2.6 on 2022-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220104_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='condition',
            field=models.CharField(default='New', max_length=20),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
