# Generated by Django 3.2.6 on 2022-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='date_creation',
            field=models.DateField(null=True),
        ),
    ]
