# Generated by Django 3.2.6 on 2022-01-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_watch_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='photo',
            field=models.ImageField(default='watch_cover_default', upload_to='uplaod_to/'),
        ),
    ]
