# Generated by Django 3.2.6 on 2022-01-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_watch_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='photo',
            field=models.ImageField(default='watch_cover_default', upload_to='static/image/'),
        ),
    ]
